### ISSUE TITLE
Incompatibility with VanillaFix

### ISSUE THREAD

**Issue by mxnmnm** [LXGaming/MixinBootstrap#53] opened 2021-12-30 03:14 UTC
- MixinBootstrap version: 1.1.0
- Forge version: 14.23.5.2860
- Minecraft version: 1.12.2
- Java version: Java 8 
- Mods: VanillaFix

**Issue Description**
Version 1.1.0 is incompatible with VanillaFix
Log: https://gist.github.com/mxnmnm/11252ae16b01ba4a582332c4d3db5d24

**Comment by LXGaming** [comment] 2021-12-30 03:20
Duplicate of https://github.com/LXGaming/MixinBootstrap/issues/48 and https://github.com/DimensionalDevelopment/VanillaFix/issues/335

This is not something MixinBootstrap can fix, DimensionalDevelopment will need to apply the fix from https://github.com/DimensionalDevelopment/JustEnoughIDs/pull/185 to VanillaFix

**Comment by xJon** [comment] 2022-04-03 17:26
Is there any workaround for this apart from using [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter) or [Mixin 0.7-0.8 Compatibility](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility) alongside MixinBootstrap?
(I say alongside as multiple mods have MixinBootstrap as a required dependency).

**Comment by LXGaming** [comment] 2022-04-04 04:47
Oh FFS, VanillaFix uses a [custom Mixin](https://github.com/DimensionalDevelopment/VanillaFix/blob/99cb47cc05b4790e8ef02bbcac932b21dafa107f/build.gradle#L32) which would make it incompatible with everything else, I'll look into this and see what fixes are possible.

**Comment by LXGaming** [comment] 2022-04-04 07:12
I have no idea which VanillaFix branch they are actively developing, there are coincidentally now two Pull Requests available to them so it's up to the VanillaFix devs to sort that mess out.
- https://github.com/DimensionalDevelopment/VanillaFix/pull/344
- https://github.com/DimensionalDevelopment/VanillaFix/pull/343

I've created a release [VanillaFix v1.1.1-SNAPSHOT](https://github.com/LXGaming/VanillaFix/releases/tag/v1.1.1-SNAPSHOT) however be aware this was created based on the master branch which may or may not be the correct branch.

**Closed as completed by LXGaming** 2022-04-04 07:12 UTC

**Comment by xJon** [comment] 2022-04-04 11:34
Thank you so much for the reply! In this case, I hope the VanillaFix authors can use one of the two PR's created for them.
Thank you for also creating a build, although I am pretty sure `1.12-stable` is the branch that correlates with CurseForge's releases, and also I'm not sure whether this build would be accepted in CurseForge for a public modpack.

Lastly, as a temporary workaround is there any disadvantage of combining MixinBootstrap with [MixinBooter](https://github.com/LoliKingdom/MixinBooter) for [compatibility with VanillaFix](https://github.com/LoliKingdom/MixinBooter/issues/11#event-6033680392) (alongside other mods that require MixinBootstrap)?

**Comment by LXGaming** [comment] 2022-04-04 11:45
Not that I'm aware of. MixinBootstrap just adds the Mixin library so if there is another mod handling that then you can simply remove MixinBootstrap without worrying about breaking any mods that depend on it.

**Comment by xJon** [comment] 2022-04-04 18:32
Thank you @LXGaming! I originally got CurseForge's platform dependencies confused with Forge's hard dependencies, so I found that in my case I am able to simply use MixinBooter instead.

**Comment by Natedogwoooof** [comment] 2023-12-04 20:16
i tryed downloading both of the Mixins mod and im still crashing

**Comment by LXGaming** [comment] 2023-12-04 22:50
> i tryed downloading both of the Mixins mod and im still crashing

@Natedogwoooof Create a new issue and provide your `debug.log`

**Comment by itsmeow** [comment] 2026-07-22 12:01
For you lost souls out there on the internet, needing the fixed jar that was never released: [VanillaFix-1.0.11.zip](https://github.com/user-attachments/files/30267404/VanillaFix-1.0.11.zip)

Rename to .jar of course
