### ISSUE TITLE
crash at startup

### ISSUE THREAD

**Issue by christomite** [LXGaming/MixinBootstrap#19] opened 2020-06-06 12:57 UTC
when i remove bootstrap it works fine 
[crash-2020-06-06_07.54.13-client.txt](https://github.com/LXGaming/MixinBootstrap/files/4740040/crash-2020-06-06_07.54.13-client.txt)
[debug.log](https://github.com/LXGaming/MixinBootstrap/files/4740043/debug.log)

**Comment by LXGaming** [comment] 2020-06-07 03:25
Duplicate of #18. Update OptiForge to MC1.15.2-0.1.21 as that version is compatible with OptiFine v1.15.2_HD_U_G1_pre21

**Closed as completed** 2020-06-09 03:57 UTC
