### ISSUE TITLE
using multiple Minecraft mods that need MixinBootstrap will crash/freeze game

### ISSUE THREAD

**Issue by MilkissWhite** [LXGaming/MixinBootstrap#5] opened 2020-02-18 11:12 UTC
minecraft 1.15.2
forge 31.1.12 (31.1.0 also tested)
MixinBootstrap (1.0.1 / 1.0.2 tested)

mod A "water-erosion-1.15.2-forge-1.0.1" (Water Erosion)
mod B "immersive-portals-0.4(for+mc+1.15+with+forge)" (Immersive portals)
mod C "enchantmentcontrol-1.0" (Enchantment control)
all three mods need MixinBootstrap

A+B make crash at FML early loading progress.
A+C or B+C make freezing game when start world-loading. both case Create New World and Load Saved World will not start(not showing square image and percentage)

**Comment by LXGaming** [comment] 2020-02-18 12:05
The first issue with `water-erosion` and `immersive-portals` crashing super early is due to both of these mods naming their refmap files `main.refmap.json`, These files overwrite each other and as a result it can cause the Mixin mappings to go missing. The developers of theses mods should be naming their refmap so they are unique, this is as simple as putting the mod id in the file name.

The second issue I'm blaming on `enchantmentcontrol` as attempting to load a single player world with only it and `MixinBootstrap` results in it dumping Mixin errors in the `debug.log`, Looking at the GitHub repository for [Tfarcenim/EnchantmentControl](https://github.com/Tfarcenim/EnchantmentControl) I'd guess that the issue is due to the fact the mod is written for 1.15.1 and not 1.15.2.

I was able to patch `water-erosion` by modifying the json files contained within the jar in order to make the refmap unique and successfully ran both it and `immersive-portals` with no issues.

**Comment by MilkissWhite** [comment] 2020-02-18 13:44
thank you for detail infomation

**Comment by LXGaming** [comment] 2020-02-19 00:29
First issue has been fixed in `water-erosion v1.0.2`.

The second issue is something that needs to be fixed by the `enchantmentcontrol` developer.

**Closed as completed by LXGaming** 2020-02-19 00:29 UTC
